-- Chat system tables for ElasticDash Backend
-- PostgreSQL compatible schema

-- ============================================================
-- Drop tables in reverse dependency order
-- ============================================================
DROP TABLE IF EXISTS ChatSessions CASCADE;
DROP TABLE IF EXISTS ChatPlanSteps CASCADE;
DROP TABLE IF EXISTS ChatPlans CASCADE;
DROP TABLE IF EXISTS ChatFeedbackReasons CASCADE;
DROP TABLE IF EXISTS ChatFeedback CASCADE;
DROP TABLE IF EXISTS ChatMessages CASCADE;
DROP TABLE IF EXISTS Conversations CASCADE;

-- ============================================================
-- Conversations table - Groups messages into conversations
-- ============================================================
CREATE TABLE IF NOT EXISTS Conversations (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    customer_user_id VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id)
);

-- ============================================================
-- Chat Messages table - Individual messages in a conversation
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatMessages (
    id SERIAL PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES Conversations(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    customer_user_id VARCHAR(255),
    plan_id INT,
    role VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(50),
    metadata JSONB,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id)
);

-- ============================================================
-- Chat Feedback table - Like/dislike reactions on messages
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatFeedback (
    id SERIAL PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES ChatMessages(id) ON DELETE CASCADE,
    conversation_id INTEGER NOT NULL REFERENCES Conversations(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    feedback_type VARCHAR(50) NOT NULL,
    is_helpful BOOLEAN,
    status VARCHAR(50) DEFAULT 'active',
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id),
    UNIQUE(message_id, user_id)
);

-- ============================================================
-- Chat Feedback Reasons table - Details about dislikes
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatFeedbackReasons (
    id SERIAL PRIMARY KEY,
    feedback_id INTEGER NOT NULL REFERENCES ChatFeedback(id) ON DELETE CASCADE,
    reason_category VARCHAR(100) NOT NULL,
    description TEXT,
    expected_response TEXT,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id)
);

-- ============================================================
-- Chat Plans table - Store execution plans generated by planner
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatPlans (
    id SERIAL PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES Conversations(id) ON DELETE CASCADE,
    user_message_id INTEGER REFERENCES ChatMessages(id),
    plan_json JSONB NOT NULL,
    intent_type VARCHAR(50),
    status VARCHAR(50) DEFAULT 'pending',
    needs_approval BOOLEAN DEFAULT TRUE,
    approved_at TIMESTAMP WITH TIME ZONE,
    approved_by INTEGER REFERENCES users(id),
    rejected_at TIMESTAMP WITH TIME ZONE,
    rejected_by INTEGER REFERENCES users(id),
    rejection_reason TEXT,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id)
);

-- ============================================================
-- Chat Plan Steps table - Track execution of individual steps
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatPlanSteps (
    id SERIAL PRIMARY KEY,
    plan_id INTEGER NOT NULL REFERENCES ChatPlans(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    description TEXT,
    api_path VARCHAR(255),
    api_method VARCHAR(50),
    api_request_json JSONB,
    api_response_json JSONB,
    status VARCHAR(50) DEFAULT 'pending',
    error_message TEXT,
    duration_ms INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Chat Sessions table - Track user sessions for approval/context
-- ============================================================
CREATE TABLE IF NOT EXISTS ChatSessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    conversation_id INTEGER REFERENCES Conversations(id) ON DELETE CASCADE,
    pending_plan_id INTEGER REFERENCES ChatPlans(id),
    session_data JSONB,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Indexes for performance optimization
-- ============================================================
-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_Conversations_user_created ON Conversations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_Conversations_customer_user ON Conversations(customer_user_id) WHERE customer_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ChatMessages_conversation_created ON ChatMessages(conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ChatMessages_user_created ON ChatMessages(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ChatFeedback_message_type ON ChatFeedback(message_id, feedback_type);
CREATE INDEX IF NOT EXISTS idx_ChatPlans_conversation_status ON ChatPlans(conversation_id, status);

-- Single column indexes for filtering
CREATE INDEX IF NOT EXISTS idx_Conversations_deleted ON Conversations(deleted) WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_ChatMessages_conversation ON ChatMessages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_ChatMessages_role ON ChatMessages(role);
CREATE INDEX IF NOT EXISTS idx_ChatFeedback_conversation ON ChatFeedback(conversation_id);
CREATE INDEX IF NOT EXISTS idx_ChatPlans_status ON ChatPlans(status);
CREATE INDEX IF NOT EXISTS idx_ChatPlans_intent_type ON ChatPlans(intent_type);
CREATE INDEX IF NOT EXISTS idx_ChatPlans_deleted ON ChatPlans(deleted) WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_ChatPlanSteps_plan ON ChatPlanSteps(plan_id);
CREATE INDEX IF NOT EXISTS idx_ChatPlanSteps_status ON ChatPlanSteps(status);
CREATE INDEX IF NOT EXISTS idx_ChatSessions_user ON ChatSessions(user_id);
CREATE INDEX IF NOT EXISTS idx_ChatSessions_expires ON ChatSessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_ChatFeedbackReasons_feedback ON ChatFeedbackReasons(feedback_id);
CREATE INDEX IF NOT EXISTS idx_ChatFeedbackReasons_category ON ChatFeedbackReasons(reason_category);
